/**
 * Backend GraphQL module catalog for e2e smoke (valid GraphQL only).
 */
export type BackendModuleSmoke = {
  module: string
  queryName: string | null
  smokeQuery: string | null
  usesOrganizationId: boolean
  skipReason: string | null
}

export const BACKEND_MODULES: BackendModuleSmoke[] = [
  {
    module: "allocation-schedule",
    queryName: "allocationSchedules",
    smokeQuery: "query BackendSmoke_allocation_schedule($organizationId: String!) { allocationSchedules(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "applicant",
    queryName: "applicants",
    smokeQuery: "query BackendSmoke_applicant($organizationId: String!) { applicants(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "appraisal",
    queryName: "appraisals",
    smokeQuery: "query BackendSmoke_appraisal($organizationId: String!) { appraisals(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "approval",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "No GraphQL schema (internal/shared module)",
  },
  {
    module: "approval-request",
    queryName: "myApprovalRequests",
    smokeQuery: "query BackendSmoke_approval_request { myApprovalRequests { __typename } }",
    usesOrganizationId: false,
    skipReason: null,
  },
  {
    module: "asset",
    queryName: "assets",
    smokeQuery: "query BackendSmoke_asset($organizationId: String!) { assets(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "asset-maintenance",
    queryName: "assetMaintenances",
    smokeQuery: "query BackendSmoke_asset_maintenance($organizationId: ID!) { assetMaintenances(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "attendance",
    queryName: "attendances",
    smokeQuery: "query BackendSmoke_attendance($organizationId: ID!) { attendances(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "attribute",
    queryName: "attributes",
    smokeQuery: "query BackendSmoke_attribute($organizationId: ID!) { attributes(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "audit-log",
    queryName: "auditLogs",
    smokeQuery: "query BackendSmoke_audit_log { auditLogs { __typename } }",
    usesOrganizationId: false,
    skipReason: null,
  },
  {
    module: "auth",
    queryName: "me",
    smokeQuery: "query BackendSmoke_auth { me { id email } }",
    usesOrganizationId: false,
    skipReason: null,
  },
  {
    module: "bank",
    queryName: "banks",
    smokeQuery: "query BackendSmoke_bank($organizationId: ID!) { banks(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "base",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "No GraphQL schema (internal/shared module)",
  },
  {
    module: "blanket-order",
    queryName: "blanketOrders",
    smokeQuery: "query BackendSmoke_blanket_order($organizationId: ID!) { blanketOrders(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "bom",
    queryName: "billsOfMaterials",
    smokeQuery: "query BackendSmoke_bom($organizationId: ID!) { billsOfMaterials(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "budget",
    queryName: "budgets",
    smokeQuery: "query BackendSmoke_budget($organizationId: String!) { budgets(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "career",
    queryName: "careers",
    smokeQuery: "query BackendSmoke_career($organizationId: String!) { careers(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "cash-bank",
    queryName: "cashBanks",
    smokeQuery: "query BackendSmoke_cash_bank($organizationId: String!) { cashBanks(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "client",
    queryName: "clients",
    smokeQuery: "query BackendSmoke_client($organizationId: ID) { clients(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "contractor",
    queryName: "contractors",
    smokeQuery: "query BackendSmoke_contractor($organizationId: String!) { contractors(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "counter",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "No GraphQL schema (internal/shared module)",
  },
  {
    module: "currency-revaluation",
    queryName: "currencyRevaluations",
    smokeQuery: "query BackendSmoke_currency_revaluation($organizationId: String!) { currencyRevaluations(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "customer",
    queryName: "customers",
    smokeQuery: "query BackendSmoke_customer($organizationId: String!) { customers(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "customer-deposit",
    queryName: "customerDeposits",
    smokeQuery: "query BackendSmoke_customer_deposit($organizationId: ID!) { customerDeposits(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "customer-invoice",
    queryName: "customerinvoices",
    smokeQuery: "query BackendSmoke_customer_invoice($organizationId: ID!) { customerinvoices(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "customer-payment",
    queryName: "customerPayments",
    smokeQuery: "query BackendSmoke_customer_payment($organizationId: ID!) { customerPayments(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "customer-refund",
    queryName: "customerRefunds",
    smokeQuery: "query BackendSmoke_customer_refund($organizationId: ID!) { customerRefunds(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "customer-statement",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "Requires real customerId fixture",
  },
  {
    module: "delivery-challan",
    queryName: "deliverychallans",
    smokeQuery: "query BackendSmoke_delivery_challan($organizationId: String!) { deliverychallans(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "delivery-order",
    queryName: "deliveryOrders",
    smokeQuery: "query BackendSmoke_delivery_order($organizationId: ID!) { deliveryOrders(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "document",
    queryName: "organizationDocuments",
    smokeQuery: "query BackendSmoke_document($organizationId: ID!) { organizationDocuments(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "dvs",
    queryName: "dvsRecords",
    smokeQuery: "query BackendSmoke_dvs($organizationId: String!) { dvsRecords(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "employee-master",
    queryName: "employeeMasters",
    smokeQuery: "query BackendSmoke_employee_master($organizationId: ID!) { employeeMasters(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "employee-salary-structure",
    queryName: "employeeSalaryStructures",
    smokeQuery: "query BackendSmoke_employee_salary_structure($organizationId: String!) { employeeSalaryStructures(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "epm",
    queryName: "epms",
    smokeQuery: "query BackendSmoke_epm($organizationId: String!) { epms(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "excise-invoice",
    queryName: "exciseinvoices",
    smokeQuery: "query BackendSmoke_excise_invoice($organizationId: String!) { exciseinvoices(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "extraction",
    queryName: "extractions",
    smokeQuery: "query BackendSmoke_extraction($organizationId: String!) { extractions(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "finance-charge-assessment",
    queryName: "financeChargeAssessments",
    smokeQuery: "query BackendSmoke_finance_charge_assessment($organizationId: String!) { financeChargeAssessments(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "fixed-asset",
    queryName: "fixedAssets",
    smokeQuery: "query BackendSmoke_fixed_asset($organizationId: ID!) { fixedAssets(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "general-ledger",
    queryName: "generalLedgers",
    smokeQuery: "query BackendSmoke_general_ledger($organizationId: String!) { generalLedgers(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "global-search",
    queryName: "globalSearch",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: query (primary: globalSearch)",
  },
  {
    module: "goods-receipt",
    queryName: "goodsreceipts",
    smokeQuery: "query BackendSmoke_goods_receipt($organizationId: String!) { goodsreceipts(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "grn",
    queryName: "grns",
    smokeQuery: "query BackendSmoke_grn($organizationId: ID!) { grns(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "hr-master",
    queryName: "hrMasters",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: kind (primary: hrMasters)",
  },
  {
    module: "individual-price-list",
    queryName: "individualPriceLists",
    smokeQuery: "query BackendSmoke_individual_price_list($organizationId: String!) { individualPriceLists(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "intercompany-allocation",
    queryName: "intercompanyAllocations",
    smokeQuery: "query BackendSmoke_intercompany_allocation($organizationId: ID!) { intercompanyAllocations(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "intercompany-journal",
    queryName: "intercompanyJournalEntries",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: originatingOrganizationId (primary: intercompanyJournalEntries)",
  },
  {
    module: "intercompany-transfer",
    queryName: "intercompanyTransfers",
    smokeQuery: "query BackendSmoke_intercompany_transfer($organizationId: ID!) { intercompanyTransfers(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "internal-order",
    queryName: "internalorders",
    smokeQuery: "query BackendSmoke_internal_order($organizationId: String!) { internalorders(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "inventory-control",
    queryName: "lowStockItems",
    smokeQuery: "query BackendSmoke_inventory_control($organizationId: String!) { lowStockItems(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "inventory-return",
    queryName: "inventoryreturns",
    smokeQuery: "query BackendSmoke_inventory_return($organizationId: String!) { inventoryreturns(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "ip-inspection",
    queryName: "ipinspections",
    smokeQuery: "query BackendSmoke_ip_inspection($organizationId: String!) { ipinspections(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "item",
    queryName: "items",
    smokeQuery: "query BackendSmoke_item($organizationId: ID!) { items(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "journal-entry",
    queryName: "journalEntries",
    smokeQuery: "query BackendSmoke_journal_entry($organizationId: String!) { journalEntries(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "lead",
    queryName: "leads",
    smokeQuery: "query BackendSmoke_lead($organizationId: String!) { leads(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "leave",
    queryName: "leaveTypes",
    smokeQuery: "query BackendSmoke_leave($organizationId: ID!) { leaveTypes(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "loan-repayment",
    queryName: "loanrepayments",
    smokeQuery: "query BackendSmoke_loan_repayment($organizationId: String!) { loanrepayments(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "material-receipt",
    queryName: "materialreceipts",
    smokeQuery: "query BackendSmoke_material_receipt($organizationId: ID!) { materialreceipts(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "module-workspace-record",
    queryName: "moduleWorkspaceRecords",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: routePath (primary: moduleWorkspaceRecords)",
  },
  {
    module: "notification",
    queryName: "myNotifications",
    smokeQuery: "query BackendSmoke_notification { myNotifications(limit: 1) { __typename } }",
    usesOrganizationId: false,
    skipReason: null,
  },
  {
    module: "onboarding",
    queryName: "onboardings",
    smokeQuery: "query BackendSmoke_onboarding($organizationId: String!) { onboardings(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "opportunity",
    queryName: "opportunities",
    smokeQuery: "query BackendSmoke_opportunity($organizationId: String!) { opportunities(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "organization",
    queryName: "organizations",
    smokeQuery: "query BackendSmoke_organization { organizations(limit: 1) { __typename } }",
    usesOrganizationId: false,
    skipReason: null,
  },
  {
    module: "package",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "Platform admin only (packages)",
  },
  {
    module: "package-assignment",
    queryName: "packageModuleAssignments",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: packageId (primary: packageModuleAssignments)",
  },
  {
    module: "payment-term",
    queryName: "paymentTerms",
    smokeQuery: "query BackendSmoke_payment_term($organizationId: ID!) { paymentTerms(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "payroll-management",
    queryName: "payrollmanagements",
    smokeQuery: "query BackendSmoke_payroll_management($organizationId: String!) { payrollmanagements(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "payroll-ui-record",
    queryName: "payrolluirecords",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: category (primary: payrolluirecords)",
  },
  {
    module: "payslip",
    queryName: "payslip",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: id (primary: payslip)",
  },
  {
    module: "pdf",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "No GraphQL schema (internal/shared module)",
  },
  {
    module: "price-list",
    queryName: "priceLists",
    smokeQuery: "query BackendSmoke_price_list($organizationId: String!) { priceLists(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "product",
    queryName: "products",
    smokeQuery: "query BackendSmoke_product($organizationId: ID!) { products(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "product-category",
    queryName: "productCategories",
    smokeQuery: "query BackendSmoke_product_category($organizationId: ID!) { productCategories(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "product-stock",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "No GraphQL schema (internal/shared module)",
  },
  {
    module: "product-variant",
    queryName: "productVariant",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: id (primary: productVariant)",
  },
  {
    module: "production-planning",
    queryName: "productionplannings",
    smokeQuery: "query BackendSmoke_production_planning($organizationId: String!) { productionplannings(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "project",
    queryName: "projects",
    smokeQuery: "query BackendSmoke_project($organizationId: ID!) { projects(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "purchase-order",
    queryName: "purchaseorders",
    smokeQuery: "query BackendSmoke_purchase_order($organizationId: ID!) { purchaseorders(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "quality-control",
    queryName: "qcInspections",
    smokeQuery: "query BackendSmoke_quality_control($organizationId: ID!) { qcInspections(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "quotation",
    queryName: "quotations",
    smokeQuery: "query BackendSmoke_quotation($organizationId: ID) { quotations(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "return-authorization",
    queryName: "returnAuthorizations",
    smokeQuery: "query BackendSmoke_return_authorization($organizationId: String!) { returnAuthorizations(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "role",
    queryName: null,
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "Requires elevated role permission (read on role)",
  },
  {
    module: "salary-processing",
    queryName: "salaryprocessings",
    smokeQuery: "query BackendSmoke_salary_processing($organizationId: String!) { salaryprocessings(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "sales-enquiry",
    queryName: "salesEnquiries",
    smokeQuery: "query BackendSmoke_sales_enquiry($organizationId: ID!) { salesEnquiries(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "sales-order",
    queryName: "salesorders",
    smokeQuery: "query BackendSmoke_sales_order($organizationId: ID!) { salesorders(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "sales-quotation",
    queryName: "salesQuotations",
    smokeQuery: "query BackendSmoke_sales_quotation($organizationId: ID!) { salesQuotations(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "sales-return",
    queryName: "salesreturns",
    smokeQuery: "query BackendSmoke_sales_return($organizationId: String!) { salesreturns(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "site-location",
    queryName: "siteLocations",
    smokeQuery: "query BackendSmoke_site_location($organizationId: String!) { siteLocations(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "stock-adjustment",
    queryName: "stockadjustments",
    smokeQuery: "query BackendSmoke_stock_adjustment($organizationId: ID!) { stockadjustments(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "stock-transfer",
    queryName: "stocktransfers",
    smokeQuery: "query BackendSmoke_stock_transfer($organizationId: ID!) { stocktransfers(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "tag",
    queryName: "tags",
    smokeQuery: "query BackendSmoke_tag($organizationId: ID!) { tags(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "tax-compliance",
    queryName: "checkGstinStatus",
    smokeQuery: null,
    usesOrganizationId: false,
    skipReason: "List query requires fixtures: gstin (primary: checkGstinStatus)",
  },
  {
    module: "tax-rate",
    queryName: "taxRates",
    smokeQuery: "query BackendSmoke_tax_rate($organizationId: ID!) { taxRates(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "timesheet",
    queryName: "timesheetEntries",
    smokeQuery: "query BackendSmoke_timesheet($organizationId: ID!) { timesheetEntries(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "uom",
    queryName: "uoms",
    smokeQuery: "query BackendSmoke_uom($organizationId: ID!) { uoms(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "user",
    queryName: "usersByOrganization",
    smokeQuery: "query BackendSmoke_user($organizationId: ID!) { usersByOrganization(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "vendor",
    queryName: "vendors",
    smokeQuery: "query BackendSmoke_vendor($organizationId: ID!) { vendors(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "vendor-bill",
    queryName: "vendorBills",
    smokeQuery: "query BackendSmoke_vendor_bill($organizationId: ID!) { vendorBills(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "vendor-credit",
    queryName: "vendorCredits",
    smokeQuery: "query BackendSmoke_vendor_credit($organizationId: ID!) { vendorCredits(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "vendor-debit-note",
    queryName: "vendorDebitNotes",
    smokeQuery: "query BackendSmoke_vendor_debit_note($organizationId: ID!) { vendorDebitNotes(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "vendor-payment",
    queryName: "vendorPayments",
    smokeQuery: "query BackendSmoke_vendor_payment($organizationId: ID!) { vendorPayments(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "vendor-prepayment",
    queryName: "vendorPrepayments",
    smokeQuery: "query BackendSmoke_vendor_prepayment($organizationId: ID!) { vendorPrepayments(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "warehouse",
    queryName: "warehouses",
    smokeQuery: "query BackendSmoke_warehouse($organizationId: String!) { warehouses(organizationId: $organizationId) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
  {
    module: "work-order",
    queryName: "workorders",
    smokeQuery: "query BackendSmoke_work_order($organizationId: String!) { workorders(organizationId: $organizationId, limit: 1) { __typename } }",
    usesOrganizationId: true,
    skipReason: null,
  },
]

export function backendModulesToSmoke(): BackendModuleSmoke[] {
  return BACKEND_MODULES.filter((m) => m.smokeQuery)
}

export function backendModulesSkipped(): BackendModuleSmoke[] {
  return BACKEND_MODULES.filter((m) => m.skipReason)
}

