/**
 * Complete catalog of protected frontend pages (every page.tsx under app/(protected)).
 * Dynamic routes with [param] are excluded from smoke (need fixtures).
 */
export type ModulePage = { name: string; href: string; group: string }

export const MODULE_PAGES: ModulePage[] = [
  { group: "admin", name: "Admin / Api Tester", href: "/admin/api-tester" },
  { group: "admin", name: "Admin / Audit Log", href: "/admin/audit-log" },
  { group: "admin", name: "Admin / Dashboard", href: "/admin/dashboard" },
  { group: "admin", name: "Admin / Notifications", href: "/admin/notifications" },
  { group: "admin", name: "Admin / Organizations", href: "/admin/organizations" },
  { group: "admin", name: "Admin / Packages", href: "/admin/packages" },
  { group: "admin", name: "Admin / Settings", href: "/admin/settings" },
  { group: "admin", name: "Admin / Sub Tenants", href: "/admin/sub-tenants" },
  { group: "admin", name: "Admin / Users", href: "/admin/users" },
  { group: "ai-assistant", name: "Ai Assistant / Crm", href: "/ai-assistant/crm" },
  { group: "ai-assistant", name: "Ai Assistant / Finance", href: "/ai-assistant/finance" },
  { group: "ai-assistant", name: "Ai Assistant / Hr", href: "/ai-assistant/hr" },
  { group: "ai-assistant", name: "Ai Assistant / Inventory", href: "/ai-assistant/inventory" },
  { group: "ai-assistant", name: "Ai Assistant", href: "/ai-assistant" },
  { group: "ai-assistant", name: "Ai Assistant / Payroll", href: "/ai-assistant/payroll" },
  { group: "ai-assistant", name: "Ai Assistant / Production", href: "/ai-assistant/production" },
  { group: "ai-assistant", name: "Ai Assistant / Projects", href: "/ai-assistant/projects" },
  { group: "ai-assistant", name: "Ai Assistant / Purchases", href: "/ai-assistant/purchases" },
  { group: "ai-assistant", name: "Ai Assistant / Sales", href: "/ai-assistant/sales" },
  { group: "approvals", name: "Approvals / History", href: "/approvals/history" },
  { group: "attendance", name: "Attendance", href: "/attendance" },
  { group: "banks", name: "Banks / Make Deposits", href: "/banks/make-deposits" },
  { group: "banks", name: "Banks / Reconcile Account", href: "/banks/reconcile-account" },
  { group: "banks", name: "Banks / Reconcile Bank", href: "/banks/reconcile-bank" },
  { group: "banks", name: "Banks / Reconciliation Rules", href: "/banks/reconciliation-rules" },
  { group: "banks", name: "Banks / Transfer Funds", href: "/banks/transfer-funds" },
  { group: "banks", name: "Banks / Write Checks", href: "/banks/write-checks" },
  { group: "banks", name: "Banks / Write Tax Liability", href: "/banks/write-tax-liability" },
  { group: "blanket-orders", name: "Blanket Orders", href: "/blanket-orders" },
  { group: "cash-bank", name: "Cash Bank", href: "/cash-bank" },
  { group: "clients", name: "Clients", href: "/clients" },
  { group: "crm", name: "Crm / Lead Management", href: "/crm/lead-management" },
  { group: "crm", name: "Crm / Opportunity Management", href: "/crm/opportunity-management" },
  { group: "customer-invoices", name: "Customer Invoices", href: "/customer-invoices" },
  { group: "customers", name: "Customers / Accept Payments", href: "/customers/accept-payments" },
  { group: "customers", name: "Customers / Approve Returns", href: "/customers/approve-returns" },
  { group: "customers", name: "Customers / Assess Finance Charges", href: "/customers/assess-finance-charges" },
  { group: "customers", name: "Customers / Generate Price Lists", href: "/customers/generate-price-lists" },
  { group: "customers", name: "Customers / Generate Statements", href: "/customers/generate-statements" },
  { group: "customers", name: "Customers / Individual Price List", href: "/customers/individual-price-list" },
  { group: "customers", name: "Customers / Invoice Billable", href: "/customers/invoice-billable" },
  { group: "customers", name: "Customers / Issue Refund", href: "/customers/issue-refund" },
  { group: "customers", name: "Customers / Issue Return Authorizations", href: "/customers/issue-return-authorizations" },
  { group: "customers", name: "Customers", href: "/customers" },
  { group: "customers", name: "Customers / Print Statement", href: "/customers/print-statement" },
  { group: "customers", name: "Customers / Receive Returned Order", href: "/customers/receive-returned-order" },
  { group: "customers", name: "Customers / Record Deposits", href: "/customers/record-deposits" },
  { group: "customers", name: "Customers / Refund Cash Sales", href: "/customers/refund-cash-sales" },
  { group: "dashboard", name: "Dashboard", href: "/dashboard" },
  { group: "delivery-challan", name: "Delivery Challan", href: "/delivery-challan" },
  { group: "documents", name: "Documents", href: "/documents" },
  { group: "extraction", name: "Extraction", href: "/extraction" },
  { group: "financial", name: "Financial / Advanced Intercompany Journal", href: "/financial/advanced-intercompany-journal" },
  { group: "financial", name: "Financial / Asset Maintenance", href: "/financial/asset-maintenance" },
  { group: "financial", name: "Financial / Chart Of Accounts", href: "/financial/chart-of-accounts" },
  { group: "financial", name: "Financial / Create Allocation Schedules", href: "/financial/create-allocation-schedules" },
  { group: "financial", name: "Financial / Create Intercompany Allocation", href: "/financial/create-intercompany-allocation" },
  { group: "financial", name: "Financial / Fixed Assets", href: "/financial/fixed-assets" },
  { group: "financial", name: "Financial / Intercompany Allocation", href: "/financial/intercompany-allocation" },
  { group: "financial", name: "Financial / Intercompany Journal", href: "/financial/intercompany-journal" },
  { group: "financial", name: "Financial / Make Journal Entries", href: "/financial/make-journal-entries" },
  { group: "financial", name: "Financial / Make Statis", href: "/financial/make-statis" },
  { group: "financial", name: "Financial / Revalue Currency Balances", href: "/financial/revalue-currency-balances" },
  { group: "financial", name: "Financial / Set Up Budgets", href: "/financial/set-up-budgets" },
  { group: "financial", name: "Financial / Tax Rates", href: "/financial/tax-rates" },
  { group: "general-ledger", name: "General Ledger", href: "/general-ledger" },
  { group: "goods-receipt", name: "Goods Receipt", href: "/goods-receipt" },
  { group: "grn", name: "Grn", href: "/grn" },
  { group: "hr", name: "Hr / Appraisal", href: "/hr/appraisal" },
  { group: "hr", name: "Leave / Leave Application", href: "/hr/leave/leave-application" },
  { group: "hr", name: "Leave / Leave Enrollment", href: "/hr/leave/leave-enrollment" },
  { group: "hr", name: "Leave / Leave Reinstatement", href: "/hr/leave/leave-reinstatement" },
  { group: "hr", name: "Leave / Leave Type", href: "/hr/leave/leave-type" },
  { group: "hr", name: "Masters / Asset Issue", href: "/hr/masters/asset-issue" },
  { group: "hr", name: "Masters / Asset Name List", href: "/hr/masters/asset-name-list" },
  { group: "hr", name: "Masters / Calendar Masters", href: "/hr/masters/calendar-masters" },
  { group: "hr", name: "Masters / Career Progress Salary", href: "/hr/masters/career-progress-salary" },
  { group: "hr", name: "Masters / Employee Master", href: "/hr/masters/employee-master" },
  { group: "hr", name: "Masters / Exit Process", href: "/hr/masters/exit-process" },
  { group: "hr", name: "Masters / Fwl Qualification", href: "/hr/masters/fwl-qualification" },
  { group: "hr", name: "Masters / Loan Application", href: "/hr/masters/loan-application" },
  { group: "hr", name: "Masters / Shift Master", href: "/hr/masters/shift-master" },
  { group: "hr", name: "Hr / Onboarding", href: "/hr/onboarding" },
  { group: "hr", name: "Hr / Salary Structure", href: "/hr/salary-structure" },
  { group: "hr", name: "Hr / Timesheets", href: "/hr/timesheets" },
  { group: "inventory", name: "Inventory / Adjust Inventory", href: "/inventory/adjust-inventory" },
  { group: "inventory", name: "Inventory / Adjust Inventory Worksheet", href: "/inventory/adjust-inventory-worksheet" },
  { group: "inventory", name: "Inventory / Enter Transfer Orders", href: "/inventory/enter-transfer-orders" },
  { group: "inventory", name: "Inventory / Equipment Masters", href: "/inventory/equipment-masters" },
  { group: "inventory", name: "Inventory / Intercompany Transfer", href: "/inventory/intercompany-transfer" },
  { group: "inventory", name: "Inventory / Items", href: "/inventory/items" },
  { group: "inventory", name: "Inventory", href: "/inventory" },
  { group: "inventory", name: "Inventory / Replenish Location", href: "/inventory/replenish-location" },
  { group: "inventory", name: "Inventory / Review Negative Inventory", href: "/inventory/review-negative-inventory" },
  { group: "inventory", name: "Inventory / Stock Ledger", href: "/inventory/stock-ledger" },
  { group: "inventory-control", name: "Inventory Control", href: "/inventory-control" },
  { group: "items", name: "Items", href: "/items" },
  { group: "material-receipt", name: "Material Receipt", href: "/material-receipt" },
  { group: "notifications", name: "Notifications", href: "/notifications" },
  { group: "org-admin", name: "Org Admin / Approvals", href: "/org-admin/approvals" },
  { group: "org-admin", name: "Org Admin / Dashboard", href: "/org-admin/dashboard" },
  { group: "org-admin", name: "Org Admin / Notifications", href: "/org-admin/notifications" },
  { group: "org-admin", name: "Org Admin / Roles Permissions", href: "/org-admin/roles-permissions" },
  { group: "org-admin", name: "Org Admin / Sub Tenants", href: "/org-admin/sub-tenants" },
  { group: "org-admin", name: "Org Admin / Users", href: "/org-admin/users" },
  { group: "org-admin", name: "Org Admin / Users And Roles", href: "/org-admin/users-and-roles" },
  { group: "organizations", name: "Organizations", href: "/organizations" },
  { group: "payables", name: "Payables / Approve Vendor Payments", href: "/payables/approve-vendor-payments" },
  { group: "payables", name: "Payables / Bill Purchase Orders", href: "/payables/bill-purchase-orders" },
  { group: "payables", name: "Payables / Enter Bills", href: "/payables/enter-bills" },
  { group: "payables", name: "Payables / Enter Vendor Credits", href: "/payables/enter-vendor-credits" },
  { group: "payables", name: "Payables / Enter Vendor Prepayment", href: "/payables/enter-vendor-prepayment" },
  { group: "payables", name: "Payables / Pay Bills", href: "/payables/pay-bills" },
  { group: "payroll", name: "Data Preparation / Biometric Data", href: "/payroll/data-preparation/biometric-data" },
  { group: "payroll", name: "Data Preparation / Manual Entry", href: "/payroll/data-preparation/manual-entry" },
  { group: "payroll", name: "Payroll / Data Preparation", href: "/payroll/data-preparation" },
  { group: "payroll", name: "Data Preparation / Yard Data", href: "/payroll/data-preparation/yard-data" },
  { group: "payroll", name: "Others / Loan Repayment", href: "/payroll/others/loan-repayment" },
  { group: "payroll", name: "Processing / Pay Batch", href: "/payroll/processing/pay-batch" },
  { group: "payroll", name: "Processing / Payee Employee", href: "/payroll/processing/payee-employee" },
  { group: "payroll", name: "Processing / Retroactive Payment", href: "/payroll/processing/retroactive-payment" },
  { group: "payroll", name: "Setup / Employee Pf", href: "/payroll/setup/employee-pf" },
  { group: "payroll", name: "Setup / Fwl Qualification", href: "/payroll/setup/fwl-qualification" },
  { group: "payroll", name: "Setup / Pay Component", href: "/payroll/setup/pay-component" },
  { group: "payroll", name: "Setup / Pay Group", href: "/payroll/setup/pay-group" },
  { group: "payroll", name: "Statutory / Community Fund", href: "/payroll/statutory/community-fund" },
  { group: "payroll", name: "Statutory / Cpf Age Group", href: "/payroll/statutory/cpf-age-group" },
  { group: "payroll", name: "Statutory / Ir8A Year", href: "/payroll/statutory/ir8a-year" },
  { group: "payroll", name: "Statutory / Sdl Master", href: "/payroll/statutory/sdl-master" },
  { group: "payroll", name: "Workflow / Payroll Runs", href: "/payroll/workflow/payroll-runs" },
  { group: "payroll", name: "Workflow / Timesheet Pool", href: "/payroll/workflow/timesheet-pool" },
  { group: "payroll-management", name: "Payroll Management", href: "/payroll-management" },
  { group: "production", name: "Production / Bom", href: "/production/bom" },
  { group: "production", name: "Dashboards / Mep Overall", href: "/production/dashboards/mep-overall" },
  { group: "production", name: "Dashboards / Plant Modules", href: "/production/dashboards/plant-modules" },
  { group: "production", name: "Dashboards / Workshop", href: "/production/dashboards/workshop" },
  { group: "production", name: "Drawings / Project Documents", href: "/production/drawings/project-documents" },
  { group: "production", name: "Drawings / Upload", href: "/production/drawings/upload" },
  { group: "production", name: "Masters / Contractors", href: "/production/masters/contractors" },
  { group: "production", name: "Masters / Project Masters", href: "/production/masters/project-masters" },
  { group: "production", name: "Masters / Site Locations", href: "/production/masters/site-locations" },
  { group: "production", name: "Production / Module Time Tracking", href: "/production/module-time-tracking" },
  { group: "production", name: "Production", href: "/production" },
  { group: "production", name: "Production / Quality", href: "/production/quality" },
  { group: "production", name: "Production / Scan Qr Code", href: "/production/scan-qr-code" },
  { group: "production", name: "Production / Status All Modules", href: "/production/status-all-modules" },
  { group: "production-planning", name: "Production Planning", href: "/production-planning" },
  { group: "products", name: "Products / Attributes", href: "/products/attributes" },
  { group: "products", name: "Products / Categories", href: "/products/categories" },
  { group: "products", name: "Products", href: "/products" },
  { group: "products", name: "Products / Uom", href: "/products/uom" },
  { group: "project-management", name: "Project Management / Gantt Chart", href: "/project-management/gantt-chart" },
  { group: "project-management", name: "Project Management / Milestones", href: "/project-management/milestones" },
  { group: "project-management", name: "Project Management / Project Masters", href: "/project-management/project-masters" },
  { group: "project-management", name: "Project Management / Reports Analytics", href: "/project-management/reports-analytics" },
  { group: "project-management", name: "Project Management / Resources", href: "/project-management/resources" },
  { group: "project-management", name: "Project Management / Tasks", href: "/project-management/tasks" },
  { group: "projects", name: "Projects", href: "/projects" },
  { group: "purchase-orders", name: "Purchase Orders", href: "/purchase-orders" },
  { group: "purchases", name: "Purchases / Debit Note", href: "/purchases/debit-note" },
  { group: "purchases", name: "Purchases / Delivery Order", href: "/purchases/delivery-order" },
  { group: "purchases", name: "Purchases / Enter Purchase Orders", href: "/purchases/enter-purchase-orders" },
  { group: "purchases", name: "Purchases / Order Requisition", href: "/purchases/order-requisition" },
  { group: "purchases", name: "Purchases / Purchase Requisition", href: "/purchases/purchase-requisition" },
  { group: "purchases", name: "Purchases / Receive Orders", href: "/purchases/receive-orders" },
  { group: "quotations", name: "Quotations", href: "/quotations" },
  { group: "quotations", name: "Quotations / Send", href: "/quotations/send" },
  { group: "reports", name: "Financial / Aged Payable", href: "/reports/financial/aged-payable" },
  { group: "reports", name: "Financial / Aged Receivable", href: "/reports/financial/aged-receivable" },
  { group: "reports", name: "Financial / Balance Sheet", href: "/reports/financial/balance-sheet" },
  { group: "reports", name: "Financial / Cash Flow", href: "/reports/financial/cash-flow" },
  { group: "reports", name: "Financial / General Ledger", href: "/reports/financial/general-ledger" },
  { group: "reports", name: "Financial / Income Statement", href: "/reports/financial/income-statement" },
  { group: "reports", name: "Financial / Transaction Detail", href: "/reports/financial/transaction-detail" },
  { group: "reports", name: "Financial / Trial Balance", href: "/reports/financial/trial-balance" },
  { group: "reports", name: "Inventory / Low Stock", href: "/reports/inventory/low-stock" },
  { group: "reports", name: "Inventory / Profitability", href: "/reports/inventory/profitability" },
  { group: "reports", name: "Inventory / Stock Movement", href: "/reports/inventory/stock-movement" },
  { group: "reports", name: "Inventory / Summary", href: "/reports/inventory/summary" },
  { group: "reports", name: "Inventory / Valuation", href: "/reports/inventory/valuation" },
  { group: "salary-processing", name: "Salary Processing", href: "/salary-processing" },
  { group: "sales", name: "Sales / Create Invoices", href: "/sales/create-invoices" },
  { group: "sales", name: "Sales / Delivery Order", href: "/sales/delivery-order" },
  { group: "sales", name: "Sales / Delivery Orders", href: "/sales/delivery-orders" },
  { group: "sales", name: "Sales / Enter Cash Sales", href: "/sales/enter-cash-sales" },
  { group: "sales", name: "Sales / Enter Sales Order", href: "/sales/enter-sales-order" },
  { group: "sales", name: "Sales / Invoice Sales Order", href: "/sales/invoice-sales-order" },
  { group: "sales", name: "Sales / Issue Credit Memos", href: "/sales/issue-credit-memos" },
  { group: "sales", name: "Sales", href: "/sales" },
  { group: "sales", name: "Sales / Project", href: "/sales/project" },
  { group: "sales", name: "Sales / Sales Enquiry", href: "/sales/sales-enquiry" },
  { group: "sales-orders", name: "Sales Orders", href: "/sales-orders" },
  { group: "sales-returns", name: "Sales Returns", href: "/sales-returns" },
  { group: "settings", name: "Settings", href: "/settings" },
  { group: "stock-adjustments", name: "Stock Adjustments", href: "/stock-adjustments" },
  { group: "stock-transfers", name: "Stock Transfers", href: "/stock-transfers" },
  { group: "users", name: "Users", href: "/users" },
  { group: "vendor-payments", name: "Vendor Payments", href: "/vendor-payments" },
  { group: "vendors", name: "Vendors", href: "/vendors" },
  { group: "warehouse", name: "Warehouse", href: "/warehouse" },
  { group: "work-orders", name: "Work Orders", href: "/work-orders" },
  { group: "workflow", name: "Workflow", href: "/workflow" },
]

export function moduleGroups(): string[] {
  return [...new Set(MODULE_PAGES.map((p) => p.group))]
}

